export const AXIOS_LOGIN_LOADING = 'AXIOS_LOGIN_LOADING'
export const AXIOS_LOGIN_SUCCESS = 'AXIOS_LOGIN_SUCCESS'
export const AXIOS_LOGIN_ERROR = 'AXIOS_LOGIN_ERROR'

export const AXIOS_GET_LOADING = 'AXIOS_GET_LOADING'
export const AXIOS_GET_SUCCESS = 'AXIOS_GET_SUCCESS'
export const AXIOS_GET_ERROR = 'AXIOS_GET_ERROR'

export const AXIOS_UPDATE_LOADING = 'AXIOS_UPDATE_LOADING'
export const AXIOS_UPDATE_SUCCESS = 'AXIOS_UPDATE_SUCCESS'
export const AXIOS_UPDATE_ERROR = 'AXIOS_UPDATE_ERROR'

export const LOGOUT = 'LOGOUT'

