export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const AXIOS_LOGIN_LOADING = 'AXIOS_LOGIN_LOADING'
export const AXIOS_LOGIN_SUCCESS = 'AXIOS_LOGIN_SUCCESS'
export const AXIOS_LOGIN_ERROR = 'AXIOS_LOGIN_ERROR'

export const AXIOS_GET_LOADING = 'AXIOS_GET_LOADING'
export const AXIOS_GET_SUCCESS = 'AXIOS_GET_SUCCESS'
export const AXIOS_GET_ERROR = 'AXIOS_GET_ERROR'